### ISSUE TITLE
Missing Fxp Require Asset dependency

### ISSUE THREAD

**Issue by mrblur** [fxpio/fxp-form-extensions#1]
Simple installation of form extensions bundle throws Unexpected "inline_script":

https://github.com/fxpio/fxp-form-extensions/blob/master/Resources/views/Form/form_div_layout_select2.html.twig#L10

Documentation of bundle does not say it is required, neither does symfony recipe install it.
Is select2 going to be dropped/replaced with Symfony 4.1, or I missed something?

**Comment by francoispluchino** [comment]
Indeed, there are traces of components that have become optional ...

**Comment by francoispluchino** [comment]
Fixed by 00c3abcb849bddd8890eff9673d1bffa6f2dc96b.
